name: pro5
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.3
  camera: ^0.10.5+5
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.5.2
  firebase_ui_firestore: ^1.5.14
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_tts: ^3.8.5
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.2.1
  gradient_borders: ^1.0.0
  http: ^1.2.1
  image_picker: ^1.0.4
  location: ^5.0.3
  permission_handler: ^11.0.1
  raised_buttons: ^0.0.2
  responsive_sizer: ^3.3.0+1
  sqflite: ^2.3.0
  tflite_flutter: ^0.10.3
  tflite_v2: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/core/assets/images/logos.png"
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/core/assets/images/
    - lib/core/assets/models/
  fonts:
    - family: Koh
      fonts:
        - asset: lib/core/assets/fonts/Koh_Santepheap/KohSantepheap-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
