// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY604yMedNrbI5nnScPB5DD2SilxuhL2s',
    appId: '1:124767553878:android:d121b5ed828bfa04faaef7',
    messagingSenderId: '124767553878',
    projectId: 'login-fa7d5',
    storageBucket: 'login-fa7d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzoXmO2R4rbFyqgCLPg8GIDq31POGx37Y',
    appId: '1:124767553878:ios:61e169b062700241faaef7',
    messagingSenderId: '124767553878',
    projectId: 'login-fa7d5',
    storageBucket: 'login-fa7d5.appspot.com',
    androidClientId: '124767553878-egkvjs5dapbh5likkguoaqrck1a649h6.apps.googleusercontent.com',
    iosClientId: '124767553878-0ve9r6oq8uhjim0rntq5uifs2mlh1g8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro5',
  );
}
